### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by KingDGrizzle** [JohnnyTheTank/youtube-channel-name-converter#1]
Hey!

Your website seems to be broken, or completely bugged. I cannot get my Id nor my friends ID at all. I've tried the name, it just says "No matching channel"

**Comment by JohnnyTheTank** [comment]
should work. which name for example?

**Comment by KingDGrizzle** [comment]
Lets say, `Flich`, or `Da532`

**Comment by JohnnyTheTank** [comment]
![image](https://cloud.githubusercontent.com/assets/6803264/23338083/47c0a738-fc01-11e6-9521-485a0c869251.png)
... you can see, it's not about this tool, it's about this userid. it doesn't exists
