### ISSUE TITLE
api key restriction

### ISSUE THREAD

**Issue by porjo** [JohnnyTheTank/youtube-channel-name-converter#2]
Thanks for the app.

You may want to consider locking down where your API key can be used from to prevent abuse - see https://console.developers.google.com/apis/credentials/key/

![screenshot from 2017-05-04 07-14-03](https://cloud.githubusercontent.com/assets/1296987/25681905/67cb4214-3099-11e7-820d-7f065c0273ce.png)

**Comment by JohnnyTheTank** [comment]
Ty, just done :)
