### ISSUE TITLE
The API key is exposed

### ISSUE THREAD

**Issue by peter279k** [JohnnyTheTank/youtube-channel-name-converter#3]
As title, I think the key is not proper for being exposed in this [file](http://johnnythetank.github.io/youtube-channel-name-converter/js/app.js).

Thanks.

**Comment by chase-moskal** [comment]
@peter279k — i don't think it should be a concern

the api key is disposable, and also, in google's console he can restrict usage so that google will only accept requests for that key which originate from his domain name (eg, johnnythetank.github.io/*)

**Comment by JohnnyTheTank** [comment]
correct. but ty
